### ISSUE TITLE
does not allow connections to servers

### ISSUE THREAD

**Issue by yikescg** [PlatinPython/RGBBlocks#1]
minecraft version 1.16.5
forge 36.1.4

when included in a modpack for a server, attempting to connect to the server produces the error "internal exception: io.netty.handler.codec.encoderexception: java.lang.nullpointerexception"

**Steps to Reproduce**
run a forge server with this as one of the mods and attempt to connect

**Comment by PlatinPython** [comment]
Could you please provide both a server and a client log?

**Comment by yikescg** [comment]
I got two server and client logs each and idk if you want debug or the dated one

client:
[2021-05-29-1.log.gz](https://github.com/PlatinPython/RGBBlocks/files/6565568/2021-05-29-1.log.gz)
[debug-1.log.gz](https://github.com/PlatinPython/RGBBlocks/files/6565571/debug-1.log.gz)

server:
[2021-05-30-1.log.gz](https://github.com/PlatinPython/RGBBlocks/files/6565572/2021-05-30-1.log.gz)
[debug-1.log.gz](https://github.com/PlatinPython/RGBBlocks/files/6565573/debug-1.log.gz)

**Comment by PlatinPython** [comment]
Well I don't see anything that would suggest my mod as the culprit at the moment.
Can you connect without my mod in the mod list?
Or even just a vanilla server?

**Comment by PlatinPython** [comment]
I couldn't test this in the last 2 days.
I just tested it and I can see that there is an issue.
I will try to find the source for that and fix it as soon as I can.

**Comment by yikescg** [comment]
thanks for testing it, sorry I've been scatterbrained and couldn't check this page.
I can also try a local test for you and get back to you later, if i remember

**Comment by PlatinPython** [comment]
You don't have to, I have already found the class responsible although atm I don't know what exactly is causing the error
