### ISSUE TITLE
[Question]:  How to use RGB blocks with world-edit?

### ISSUE THREAD

**Issue by No4-KilL** [PlatinPython/RGBBlocks#10]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Question

Fow example I want to set a territory with this rgb concrete using World-edit. Is it possible?
![rgb blocks](https://user-images.githubusercontent.com/92015263/232783748-f0f9cfa5-9b6e-427e-8d04-e6a2feb963bc.jpg)

**Comment by No4-KilL** [comment]
Will you answer me?

**Comment by PlatinPython** [comment]
Yeah sorry, I didn't have time to test how you could do that until today.
I did find one way and while I don't really like it, it should be enough for your purposes
Basically:
1. Place the rgb block you want to fill the area with
2. select the block with worldedit (wooden axe)
3. run `//copy`
4. select the area you want to fill with the block (wooden axe or worldedit way of your choice)
5. run `//set #clipboard`

I did find out that worldedit has a special cased handling for some blocks (signs, player heads and spawners) that allow to set the data on those blocks. I might be able to implement such handling for rgbblocks too.

Hope that helps.

**Comment by No4-KilL** [comment]
Thank you, it helps me) It will be really cool if u will make such option
