### ISSUE TITLE
[Bug] ...Color display when installed with RubidiumExtra

### ISSUE THREAD

**Issue by Hinari27** [PlatinPython/RGBBlocks#7]
**Version Info**
- Minecraft:1.18.2
- RGB Blocks:1.1.6.1
- rubidium:0.5.4
- RubidiumExtra:0.4.11.45

**Description of the Bug**
The color of RGB Blocks is not displayed normally
**Steps to Reproduce**
Place RGB Antiblock and dye it with paint bucket
**Screenshots**
![2022-12-03_12 36 47](https://user-images.githubusercontent.com/119719124/205424030-761f4a33-2b5e-4bbe-a17f-8a9f4fc999b6.png)
Normal display

![2022-12-03_12 33 16](https://user-images.githubusercontent.com/119719124/205424057-d0da5349-e200-4309-8247-93b51e3c010a.png)
Display when RubidiumExtra is installed

**Comment by PlatinPython** [comment]
As explained in #5, this bug cannot be fixed by me.
