### ISSUE TITLE
Crash while tesselating block model

### ISSUE THREAD

**Issue by Amber-09** [PlatinPython/RGBBlocks#8]
I had been placing a concrete slab that I painted yellow around a building I was working on and I went to middle click the block to grab it and as soon as I placed it my gamed crashed

**Comment by PlatinPython** [comment]
To debug this issue I need the debug.log
It can be found in the logs folder of your minecraft folder
Please upload the file to a pastesite (e.g. https://gist.github.com) and give me the link

**Comment by PlatinPython** [comment]
Closing due to lack of feedback.
If you provide the requested information at a later date, the issue can be reopened.
