### ISSUE TITLE
[Feature]: maybe fabric port pls?

### ISSUE THREAD

**Issue by DogeTOM1143** [PlatinPython/RGBBlocks#9]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

i would like an fabric port of this amazing mod i rlly like the things yall did amazing stuff the one that u guys said for fabric aka the discontinued one is not like this one i would like this mod for fabric would be awesome!

### Ideas on how to implement it

idk maybe more blocks to get colored

**Comment by PlatinPython** [comment]
As I already said to the person asking on CurseForge, I don't have any plans to port this mod to a different mod loader.
Anyone that can read the license correctly will understand that they are free to port it themselves.
